### ISSUE TITLE
licenses?

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/test-wads#1]
Hey @JNechaevsky @kitchen-ace ,

I need your help here, please!

I'd like to maintain a repository of simple test WADs here that either of you (or anyone else) have created as a showcase to test for certain Doom source port capabilities. However, to be formally correct, I need a license attached to the published files. So, it would be great if you could agree on a license to choose for the test WADs, e.g.  CC-BY-3.0 or CC0-1.0 or similar.

Thanks!

**Comment by kitchen-ace** [comment]
Hi! I am fine with licensing all of my test wads under a public domain/CC0 license, or whatever else is most convenient for you.

As far as I remember there are no copyrighted resources in any test wad I've sent, but if there are you have my permission to replace them with FreeDoom assets (or I can, but you'll have to tell me which wads need them :p)

**Comment by fabiangreffrath** [comment]
Great, thanks! 

For now I only have `longtex2.wad` in the archive which you posted here:
https://www.doomworld.com/forum/topic/112333-this-is-woof-232-oct-19-2020-updated-winmbf/?page=6&tab=comments#comment-2143327

and `transparent_textures.wad` which you posted here (yes, that 5.5 years ago!):
https://github.com/fabiangreffrath/crispy-doom/issues/23#issue-38734048

Any other ideas?

**Comment by kitchen-ace** [comment]
I think I remember making a few others, but I can't remember what, other than one to test walking over/under monsters, which might not be important enough to include anyhow.

**Comment by JNechaevsky** [comment]
> I am fine with licensing all of my test wads under a public domain/CC0 license, or whatever else is most convenient for you.

Same for me, please choose whatever you like!

Useful created wads that's comes to mind:

* Teapot of 16 sprite rotations comes to mind: https://github.com/fabiangreffrath/crispy-doom/issues/152#issuecomment-280902515. 
* Four wads with all possible brightmap textures (except garg and lion textures, they comes to mind much later here: https://github.com/fabiangreffrath/crispy-doom/issues/334) I've made for brightmaps testing, but looks likes I've never share it - have to find it my old SourceForge repo.
* Map for checking "Oof" sound of dead player.
* Map for checking switches sound on and off (but was it improved to version 3 by @jeffdoggett?)
* Map with "Mickey mouse ears" for checking off/smooth fake contrast.
* Map for testing "blackout" when player is crushed by closed door: https://github.com/fabiangreffrath/crispy-doom/issues/257#issuecomment-359877982

Probably, it will be much faster for to recreate some maps, rather than trying to find them. Just point what exactly maps you need.

**Comment by jeffdoggett** [comment]
There's a test wad to demonstrate a bug in Acorn Doom here:

http://starfighter.acornarcade.com/mysite/doom.htm

**Comment by fabiangreffrath** [comment]
> There's a test wad to demonstrate a bug in Acorn Doom here:
> 
> http://starfighter.acornarcade.com/mysite/doom.htm

Thank you, but this is not exactly what I am looking for.

I am looking for the many small test WADs that people have contributed during the development of Crispy or related ports to highlight and check the proper function of some specific features. Also, the license terms that come with the Acorn WAD cannot really be considered free.

**Comment by fabiangreffrath** [comment]
> * Map for checking switches sound on and off (but was it improved to version 3 by @jeffdoggett?)

@jeffdoggett Which license applies to this work?

**Comment by fabiangreffrath** [comment]
What's still missing is the original longwall.wad 😢

**Comment by jeffdoggett** [comment]
I just patched the binary, never bothered to look at the licence.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, :beer: all of them, except Switches3 were recreated from scratch now:

1) Long wall wobble: [longwall.zip](https://github.com/fabiangreffrath/test-wads/files/5591566/longwall.zip)
2) Oof sound by dead player (player should kill himself with rocket launcher): [deadoof.zip](https://github.com/fabiangreffrath/test-wads/files/5591567/deadoof.zip)
3) Medusa _(careful! it silently crashes Chocolate Doom, DOS executable survives)_: [medusa.zip](https://github.com/fabiangreffrath/test-wads/files/5591590/medusa.zip)
4) Tutti-Frutti effect _(but have you seen it's effect on sprites, as I do? :stuck_out_tongue:)_: [tutti.zip](https://github.com/fabiangreffrath/test-wads/files/5591592/tutti.zip)
5) Fake contrast checking, "Mickey Mouse ears" now with different curve distances: [fakecontrast.zip](https://github.com/fabiangreffrath/test-wads/files/5591737/fakecontrast.zip)
6) Switches3.wad, we was using for checking texture changing with various applied textures to the top/middle/bottom _(note: bomb out Chocolate Doom and DOS executable with `W_CacheLumpNum: 10029773 >= numlumps` error -- because of custom flats?)_: 
[switches3.zip](https://github.com/fabiangreffrath/test-wads/files/5591773/switches3.zip)

There is still a huge slime trail case on Nuts.wad (`solidsegs` overflow?) but I'm not lucky to recreate it :(

**Comment by fabiangreffrath** [comment]
Erm, wow, thank you very much! I was initially looking to preserve the originals, but if you could recreate them, probably tune to take account of some gained knowledge of the problems, even better.

> Switches3.wad, we was using for checking texture changing with various applied textures to the top/middle/bottom (note: bomb out Chocolate Doom and DOS executable with W_CacheLumpNum: 10029773 >= numlumps error -- because of custom flats?):
switches3.zip

You will have to load this with `-merge` in Choco. Anyway, most of the switch textures will have Tutti Frutti then.

**Comment by JNechaevsky** [comment]
My pleasure! Few more ideas for evening:
* `spechits` overflow. Just a pile of sprites in one place, as well as bunch of lines.
* `visplanes` overflow. AFAIR, there are two error messages.

**Comment by JNechaevsky** [comment]
Ouch, I apologize, not this evening, too :beer:, have to celebrate my birthday. Hopefully, tomorrow! :open_mouth:

Cheers, love!

**Comment by fabiangreffrath** [comment]
Congratulations! Have a nice anniversary!

**Comment by fabiangreffrath** [comment]
> * `spechits` overflow. Just a pile of sprites in one place, as well as bunch of lines.
> * `visplanes` overflow. AFAIR, there are two error messages.

@JNechaevsky 👋 😀

**Comment by fabiangreffrath** [comment]
Oh, see, there is already this one:

https://github.com/fabiangreffrath/crispy-doom/issues/227

**Comment by JNechaevsky** [comment]
@fabiangreffrath wha-, who-, me-? 🤤 Me's still celebrating! 🍺

* `R_CheckPlane: no more visplanes` error. Just slightly rotate camera left/right: [visplanes1.zip](https://github.com/fabiangreffrath/test-wads/files/5624556/visplanes1.zip)

But how to get `R_DrawPlanes: visplane overflow (%" PRIiPTR ")` then?
